version: "3"
services:
  app:
    container_name: node_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      NODE_ENV: development
      DB_HOST: localhost:27017
      DB_USER: root
      DB_PASSWORD: nodegmp
      DB_NAME:
    depends_on:
      - mongo
    networks:
      - my_network
  mongo:
    image: "mongo"
    container_name: "nodegmp-nosql"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nodegmp
    ports:
      - '27017:27017'
    networks:
      - my_network
networks:
  my_network: